### ISSUE TITLE
xOS stuck on background

### ISSUE THREAD

**Issue by ashlandsimpson** [omarrx024/xos#13]
Hello.

When starting xOS in a virtual machine, it is just stuck on the background. On the nightly build (hours ago), it doesn't work. I really want to try out Circus web browser.

Please help.

**Comment by omarrx024** [comment]
Hi @ashlandsimpson 

I'm not aware of any issues of xOS getting stuck in the background. You mean the desktop background image, right? If so, I need to know more about the configuration you're using? Which version of xOS are you trying? Are you using the latest unstable build (disk.hdd in this repository)? Which virtual machine are you using? How much RAM? Where are you attaching the disk image (IDE, SATA?) 
To help find more debug information, configure the serial port your virtual machine to output everything to a file, and attach that file here, as it'll help me know what's going on. For QEMU, pass the command line option (-serial file:serial.txt) and attach that file. For VirtualBox, open Settings and navigate to Serial Ports. Other virtual machines will have similar options as well. 

Thanks.

**Comment by ashlandsimpson** [comment]
I am using IDE with VirtualBox. Isn't SATA the new technologies? It's working now. I tried it out on QEMU and it works. By the way, the web browser freezes.

**Comment by omarrx024** [comment]
SATA is indeed newer than IDE, but I do have read/write access for SATA hard disks: kernel/blkdev/ahci.asm. Anyway, for the web browser to work you have to emulate a compatible network card. Currently there are only drivers for RTL8139 and i8254x. In VirtualBox, go to networking settings, make sure the "attached to" field is set to NAT, and the emulated card to any one of the three Intel PRO/1000 options. For QEMU, pass the command line option `-net nic,model=e1000 -net user -net dump,file=qemudump.pcap`.

I do plan to write/port an AMD PC-NET driver someday, so that networking would work in VirtualBox with the default settings.

Cheers.

**Comment by ashlandsimpson** [comment]
The web browser does work. Google shows links like YouTube and Gmail. However, you can't do anything with the OS after that. By the way, may I say a suggestion? You should add CSS, Javascript and more HTML tags. I'm a good web developer. I can help.

Also, how did you learn to write your operating system? Did you copy some code? I would love to learn OS Development. What are good tutorials for Assembly and C?

**Comment by omarrx024** [comment]
It's okay. 

The web browser is really incomplete for now, as it's probably a week old or something. Thanks for your offer, but I prefer to write the built-in applications myself. You can write other applications if you want, helloc/helloc.c shows the basic functionality of the library, including windows, components, event handling, and other starting points all in C.

The majority of the OS is written by myself, including the kernel and user space code. There is code from other sources, of course. The i8254x network driver is mostly copied from [this driver](https://github.com/ReturnInfinity/BareMetal-OS/blob/master/os/drivers/net/i8254x.asm), and non of the fonts are made by me. Of course, FASM isn't mine either. All the code that was written by me is licensed under the MIT license, in the hope that someone could learn from it just like I learned from other projects.

I think looking for tutorials is a bad practice in general. The OSDev Wiki and forum are sufficient to get you started, even if it looks intimidating at first.

**Comment by ashlandsimpson** [comment]
Where are good places for starting? How did you actually learn?

**Comment by omarrx024** [comment]
The OSDev Wiki and forum. You learn basic skills from there, and then its mostly reading documentation combined with trial and error. Teaching yourself is the best way to learn, and to make your knowledge last longer without being forgotten.

**Comment by omarrx024** [comment]
This issue has been resolved. The problem was that the networking stack was not aware of whether there was a network driver loaded successfully or not. So, when it fails to load a driver, it would try to send/receive packets, effectively calling memory that doesn't exist, causing a page fault. My guess would be it fails on your VirtualBox when you are using the AMD PC-NET network card, because I still don't have a driver for it.
