### ISSUE TITLE
???

### ISSUE THREAD

**Issue by adamc295** [omarrx024/xos#16]
![image](https://user-images.githubusercontent.com/18663194/28670683-b44d9a54-72d1-11e7-9065-0c4b17839d97.png)
 I was played 2048, of course losing as there wasn't anything you could do in it, and then I went to launch the FASM compiler (which I had no idea how it worked), and suddenly it just did this (the image above is what happened). I was using virtual box ( v5.1.2 r 108956 to be exact). I don't know if it has anything to do with the version, but I had launched it before and put "h" in the input and then clicked "Assemble".

I hope you can get back to me, and also look at the register dump to find out what happened.

**Comment by omarrx024** [comment]
Thanks for your feedback. The log says "KERNEL PANIC: Out of physical memory." which basically means the kernel tried to allocate memory, but there wasn't enough free memory. If I were to guess, the value of EAX in the register dump suggests you have attached 64 MB of RAM to the virtual machine, and if it ran out of memory with 64 MB of RAM, it means you have too many applications running. Am I correct in guessing here? Try it with 128 MB of RAM or so, and the fault shouldn't happen, because there are no memory leaks I am aware of.

**Comment by adamc295** [comment]
Well, you were correct! I had only put 64 MB for base memory (I had no idea that it mattered.) I just wanted it working so, I had only put _that much_ on it. Thanks!
