### ISSUE TITLE
GUI Shell crash & other GUI oddities

### ISSUE THREAD

**Issue by sleephacker** [omarrx024/xos#4]
[xOS_output_2.txt](https://github.com/omarrx024/xos/files/737091/xOS_output_2.txt)
[xOS_output_1.txt](https://github.com/omarrx024/xos/files/737090/xOS_output_1.txt)

I opened as many applications as I could by repeatedly clicking 'start->button demo' and eventually the bar with the start button on it dissapeared. Interestingly, this didn't happen when opening the demo but when I clicked on the start button **after** opening lots of demo instances. I also tried it with the hello world demo and it worked I forgot to copy the file. I have also tried spamming the start button without opening any app but that didn't crash anything, and I'm pretty sure to have clicked it more times than I did with the demos. I did however find out the start menu has a weird hitbox, if I repeatedly click high on the start button it opens the menu and leaves it open, but if I repeatedly click low on the button it opens and closes the start menu. And I tried clicking on the bar first before clicking on the start button each time I opened an app, and it only crashed when I pressed the start button.

I also noticed that if you draw all the way on the rightmost pixels of the draw app your paint wraps around to the left side, probably due to overflowing to the next line in the pixel buffer.

And when I click and hold anywhere but not on a button and then drag my mouse over a button in the calculator it just spams that button, whereas if I just press and hold the button it only displays a single digit.

Finally, when I drag a window and then spastically move my mouse all over the place it behaves weird, I was able to drag my mouse out of the window while dragging the window and press other buttons, and I was also able to close the window while I was dragging it around very fast by accidentally dragging my mouse over the close button.

**Comment by omarrx024** [comment]
@sleephacker you crashed the graphical shell by opening too many windows, because (for now), the maximum windows is hard-coded 32 (and the taskbar counts as a window, so does the menu.) When there are no available free windows, the window manager returns -1, but none of my applications actually check for this.
When clicking low on the start button, it closes the menu and when you click high, it doesn't. This specific issue I am aware of, and it's written in my release notes (WM bug where frameless windows don't get "unfocused" if you click under them.)
Thanks for your feedback! I'll be sure to fix these issues soon.

**Comment by omarrx024** [comment]
@sleephacker In case you're waiting for the solution to this problem, I've solved the problem of page faulting when too many windows are opened (by increasing maximum windows to 512 -- I doubt anyone can open all that) and I also fixed the spamming buttons problem, by implementing a "drag" as a new event, instead of a click event. :)
