### ISSUE TITLE
Hangs on real HW if PS/2 mouse and keyboard are not connected

### ISSUE THREAD

**Issue by omarrx024** [omarrx024/xos#7]
Title says enough. The OS hangs if you try to boot on real HW without a PS/2 keyboard and mouse, rather than failing to initialize them and aborting. This will be fixed before the next release.

**Comment by adamc295** [comment]
I think that's happening because it EXPECTS a keyboard and mouse (but, that's probably obvious to you.) If someone code make it so that it says: `Keyboard or mouse not connected, please connect one` then they would know what to do. but now i just looked at the title and saw that it hangs with real hardware. I can't test it because my keyboard is wireless but my mouse is not (and i can't test this with real hardware because I don't have an empty disk in which to put into some hardware because i only have one computer)

**Comment by adamc295** [comment]
Now that i think about it, that was really dumb to say. Face-palm
