### ISSUE TITLE
Button does not respond twice while clicking at exactly the same position

### ISSUE THREAD

**Issue by Dev-XYS** [omarrx024/xos#8]
e.g. If I want to type '88' in the calculator, I must click '8' once then move the mouse to another position also on the button '8' and click it. Otherwise, only one '8' will be displayed.

**Comment by omarrx024** [comment]
@Dev-XYS Yes, I am aware of this issue. If you notice, it occurs only with USB mouse and not with PS/2 mouse; this is because when you unpress a button in USB mouse I don't make the window manager aware of the change, and so it thinks the user never let go of the mouse and is holding it for all that time. It'll be fixed before the next release. Thanks for your feedback anyway.

**Comment by omarrx024** [comment]
@Dev-XYS This issue has been fixed. :smiley:
